name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clippy
        run: cargo clippy --all --all-targets --locked
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: cargo test -p broken-app
  asan and tsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: asan
        env:
          RUSTFLAGS: "-Zsanitizer=address"
        run: cargo test -p broken-app -Zbuild-std --target x86_64-unknown-linux-gnu
      - name: tsan
        env:
          RUSTFLAGS: "-Zsanitizer=thread"
        run: cargo test -p broken-app -Zbuild-std --target x86_64-unknown-linux-gnu
